language: python
python:
  - "2.6"
  - "2.7"

before_install:
  - sudo add-apt-repository ppa:rethinkdb/ppa
  - sudo apt-get update -qq
  - sudo apt-get install rethinkdb

install:
  - pip install . --use-mirrors
  - pip install -r requirements.txt --use-mirrors

before_script: rethinkdb --daemon

script: nosetests rethinkORM/tests
